# Generated by Django 5.2.1 on 2025-05-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('github_url', models.URLField(blank=True, null=True)),
                ('card_title_1', models.CharField(blank=True, max_length=100)),
                ('card_desc_1', models.TextField(blank=True)),
                ('card_image_1', models.ImageField(blank=True, upload_to='cards/')),
                ('card_title_2', models.CharField(blank=True, max_length=100)),
                ('card_desc_2', models.TextField(blank=True)),
                ('card_image_2', models.ImageField(blank=True, upload_to='cards/')),
                ('tech_title_1', models.CharField(blank=True, max_length=100)),
                ('tech_desc_1', models.TextField(blank=True)),
                ('tech_icon_1', models.URLField(blank=True)),
                ('tech_title_2', models.CharField(blank=True, max_length=100)),
                ('tech_desc_2', models.TextField(blank=True)),
                ('tech_icon_2', models.URLField(blank=True)),
            ],
        ),
    ]
