# Generated by Django 5.2.1 on 2025-05-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech_desc_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_desc_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_icon_3',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_icon_4',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_title_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_title_4',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
