# Generated by Django 5.2.1 on 2025-05-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_tech_desc_3_project_tech_desc_4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='grid_image_1',
            field=models.ImageField(blank=True, upload_to='grid/'),
        ),
        migrations.AddField(
            model_name='project',
            name='grid_image_2',
            field=models.ImageField(blank=True, upload_to='grid/'),
        ),
        migrations.AddField(
            model_name='project',
            name='grid_image_3',
            field=models.ImageField(blank=True, upload_to='grid/'),
        ),
        migrations.AddField(
            model_name='project',
            name='grid_image_4',
            field=models.ImageField(blank=True, upload_to='grid/'),
        ),
    ]
